-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Mar 27, 2023 at 04:07 PM
-- Server version: 10.4.27-MariaDB
-- PHP Version: 8.0.25

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `user-registration`
--

-- --------------------------------------------------------

--
-- Table structure for table `announcements`
--

CREATE TABLE `announcements` (
  `id` int(11) NOT NULL,
  `recipient` varchar(255) DEFAULT NULL,
  `campaign` varchar(255) DEFAULT NULL,
  `status` varchar(100) NOT NULL DEFAULT 'no',
  `msg` varchar(1000) NOT NULL,
  `auther` varchar(100) NOT NULL,
  `created_at` datetime DEFAULT current_timestamp(),
  `date_send` datetime NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;

--
-- Dumping data for table `announcements`
--

INSERT INTO `announcements` (`id`, `recipient`, `campaign`, `status`, `msg`, `auther`, `created_at`, `date_send`) VALUES
(221, 'testUS', NULL, 'yes', 'hi ther WHAT', 'walid888', '2023-03-01 23:11:39', '2023-03-01 01:02:23'),
(223, 'Clarke', NULL, 'no', 'kl\nKE\nSK', 'walid888', '2023-03-01 23:08:32', '2023-03-01 01:37:30'),
(224, 'walidali', NULL, 'yes', 'hi walid . . ', 'walid888', '2023-03-01 22:49:46', '2023-03-01 01:37:55'),
(230, 'markUS', NULL, 'no', 'campaign update: your campaign is NOT_SET', 'AutoGenerated', '2023-03-02 00:17:21', '2023-03-02 00:17:21'),
(231, 'testUSa', NULL, 'no', 'campaign update: your campaign is NOT_SET', 'AutoGenerated', '2023-03-02 00:17:21', '2023-03-02 00:17:21'),
(232, 'Yoshi', NULL, 'no', 'campaign update: your campaign is NOT_SET', 'AutoGenerated', '2023-03-02 00:17:21', '2023-03-02 00:17:21'),
(233, 'Shad', NULL, 'no', 'campaign update: your campaign is NOT_SET', 'AutoGenerated', '2023-03-02 00:17:21', '2023-03-02 00:17:21'),
(234, 'Clarke', NULL, 'no', 'campaign update: your campaign is NOT_SET', 'AutoGenerated', '2023-03-02 00:17:21', '2023-03-02 00:17:21'),
(235, 'Cassandra', NULL, 'no', 'campaign update: your campaign is NOT_SET', 'AutoGenerated', '2023-03-02 00:17:21', '2023-03-02 00:17:21'),
(236, 'Ignatius', NULL, 'no', 'campaign update: your campaign is NOT_SET', 'AutoGenerated', '2023-03-02 00:17:22', '2023-03-02 00:17:22'),
(237, 'Boris', NULL, 'no', 'campaign update: your campaign is NOT_SET', 'AutoGenerated', '2023-03-02 00:17:22', '2023-03-02 00:17:22'),
(238, 'Jonas', NULL, 'no', 'campaign update: your campaign is NOT_SET', 'AutoGenerated', '2023-03-02 00:17:22', '2023-03-02 00:17:22'),
(239, 'Fulton', NULL, 'no', 'campaign update: your campaign is NOT_SET', 'AutoGenerated', '2023-03-02 00:17:22', '2023-03-02 00:17:22'),
(240, 'Dustin', NULL, 'no', 'campaign update: your campaign is NOT_SET', 'AutoGenerated', '2023-03-02 00:17:23', '2023-03-02 00:17:23'),
(241, 'Montana', NULL, 'no', 'campaign update: your campaign is NOT_SET', 'AutoGenerated', '2023-03-02 00:17:24', '2023-03-02 00:17:24'),
(245, 'markUS', NULL, 'no', 'campaign update: your campaign is tort', 'AutoGenerated', '2023-03-02 00:45:30', '2023-03-02 00:45:30'),
(246, 'frank', NULL, 'no', 'campaign update: your campaign is tort', 'AutoGenerated', '2023-03-02 00:45:30', '2023-03-02 00:45:30'),
(248, 'testUS', NULL, 'yes', 'aaa', 'walid888', '2023-03-02 00:54:52', '2023-03-02 00:54:52'),
(249, 'testUS', NULL, 'yes', 'aaad', 'walid888', '2023-03-02 00:54:56', '2023-03-02 00:54:56'),
(250, 'testUS', NULL, 'yes', 'ee', 'walid888', '2023-03-02 00:55:00', '2023-03-02 00:55:00'),
(251, 'testUS', NULL, 'yes', 'fff', 'walid888', '2023-03-02 00:55:02', '2023-03-02 00:55:02'),
(252, 'testUS', NULL, 'yes', 'cccc', 'walid888', '2023-03-02 00:55:06', '2023-03-02 00:55:06'),
(253, 'testUS', NULL, 'yes', 'hi leo', 'walid888', '2023-03-02 23:07:08', '2023-03-02 23:07:08'),
(254, 'testUS', NULL, 'yes', 'hi', 'walid888', '2023-03-03 00:07:35', '2023-03-03 00:07:35'),
(256, 'testUS', NULL, 'yes', 'how are u today\n', 'walid888', '2023-03-03 00:14:00', '2023-03-03 00:14:00'),
(257, 'testUS', NULL, 'yes', 'hi man', 'walid888', '2023-03-03 00:14:44', '2023-03-03 00:14:44'),
(258, 'testUS', NULL, 'yes', 'good job', 'walid888', '2023-03-03 00:16:10', '2023-03-03 00:15:57'),
(260, 'testUS', NULL, 'yes', 'wlis', 'walid888', '2023-03-03 00:18:30', '2023-03-03 00:18:30'),
(262, 'testUS', NULL, 'no', 'heklllsl;a', 'walid888', '2023-03-03 01:59:34', '2023-03-03 01:59:34'),
(263, 'walidali', NULL, 'yes', 'jjjj\n', 'walid888', '2023-03-03 01:59:58', '2023-03-03 01:59:58'),
(264, 'testUS', NULL, 'no', 'hhhh', 'walid888', '2023-03-03 02:00:06', '2023-03-03 02:00:06'),
(265, 'testUS', NULL, 'no', 'last sent\n', 'walid888', '2023-03-03 18:54:21', '2023-03-03 18:54:21'),
(266, 'markUS', NULL, 'no', 'last send\n', 'walid888', '2023-03-03 18:54:36', '2023-03-03 18:54:36'),
(267, 'testUS', NULL, 'no', 'kkk', 'walid888', '2023-03-03 18:54:50', '2023-03-03 18:54:50'),
(268, 'testUS', NULL, 'no', 'kpko\n', 'walid888', '2023-03-03 18:55:12', '2023-03-03 18:55:12'),
(269, 'walidali', NULL, 'yes', 'kkkk', 'walid888', '2023-03-03 18:55:18', '2023-03-03 18:55:18'),
(270, 'walidali', NULL, 'yes', 'hi\n', 'walid888', '2023-03-03 18:56:07', '2023-03-03 18:56:07'),
(271, 'walidali', NULL, 'yes', 'kelo\n', 'walid888', '2023-03-03 18:56:22', '2023-03-03 18:56:22'),
(272, 'testUS', NULL, 'no', 'kelo', 'walid888', '2023-03-03 18:56:27', '2023-03-03 18:56:27'),
(273, 'walidali', NULL, 'yes', 'hi', 'walid888', '2023-03-03 18:58:02', '2023-03-03 18:58:02'),
(274, 'walidali', NULL, 'yes', 'hi there', 'walid888', '2023-03-03 18:58:19', '2023-03-03 18:58:19'),
(275, 'walidali', NULL, 'yes', 'kelop', 'walid888', '2023-03-03 18:58:56', '2023-03-03 18:58:56'),
(276, 'broUS', NULL, 'yes', 'msg_1', 'walid888', '2023-03-03 19:05:38', '2023-03-03 19:05:38'),
(277, 'broUS', NULL, 'yes', 'msg_2', 'walid888', '2023-03-03 19:05:54', '2023-03-03 19:05:54'),
(278, 'broUS', NULL, 'yes', 'msg_3', 'walid888', '2023-03-03 19:05:58', '2023-03-03 19:05:58'),
(279, 'broUS', NULL, 'yes', 'msg_4', 'walid888', '2023-03-03 19:06:03', '2023-03-03 19:06:03'),
(280, 'broUS', NULL, 'yes', 'msg_5', 'walid888', '2023-03-03 22:06:20', '2023-03-03 19:06:10'),
(281, 'broUS', NULL, 'yes', 'msg_6', 'walid888', '2023-03-03 19:06:12', '2023-03-03 19:06:12'),
(282, 'broUS', NULL, 'yes', 'msg_7', 'walid888', '2023-03-03 19:08:06', '2023-03-03 19:08:06'),
(283, 'broUS', NULL, 'yes', 'msg_8', 'walid888', '2023-03-03 19:08:09', '2023-03-03 19:08:09'),
(284, 'broUS', NULL, 'yes', 'msg_9', 'walid888', '2023-03-03 19:08:14', '2023-03-03 19:08:14'),
(285, 'broUS', NULL, 'yes', 'msg_10', 'walid888', '2023-03-03 19:08:19', '2023-03-03 19:08:19'),
(287, 'broUS', NULL, 'yes', 'msg_11', 'walid888', '2023-03-03 22:12:36', '2023-03-03 22:12:36'),
(288, 'broUS', NULL, 'yes', 'msg_12', 'walid888', '2023-03-03 22:12:44', '2023-03-03 22:12:44'),
(289, 'broUS', NULL, 'yes', 'msg_13', 'walid888', '2023-03-03 22:12:48', '2023-03-03 22:12:48'),
(290, 'broUS', NULL, 'yes', 'msg_14', 'walid888', '2023-03-03 22:12:52', '2023-03-03 22:12:52'),
(291, 'broUS', NULL, 'yes', 'msg_15', 'walid888', '2023-03-03 22:12:57', '2023-03-03 22:12:57'),
(292, NULL, 'tort', 'yes', 'm_1', 'walid888', '2023-03-03 22:23:39', '2023-03-03 22:23:39'),
(294, NULL, 'tort', 'yes', 'm_2', 'walid888', '2023-03-03 22:29:22', '2023-03-03 22:29:22'),
(295, NULL, 'tort', 'yes', 'm_3', 'walid888', '2023-03-03 22:29:25', '2023-03-03 22:29:25'),
(296, NULL, 'tort', 'yes', 'm_4', 'walid888', '2023-03-03 22:29:27', '2023-03-03 22:29:27'),
(297, NULL, 'tort', 'yes', 'm_5', 'walid888', '2023-03-03 22:29:30', '2023-03-03 22:29:30'),
(298, NULL, 'tort', 'yes', 'm_6', 'walid888', '2023-03-03 22:29:33', '2023-03-03 22:29:33'),
(299, NULL, 'tort', 'yes', 'm_7', 'walid888', '2023-03-03 22:29:37', '2023-03-03 22:29:37'),
(300, NULL, 'tort', 'yes', 'm_8', 'walid888', '2023-03-03 22:29:40', '2023-03-03 22:29:40'),
(301, NULL, 'tort', 'yes', 'm_9', 'walid888', '2023-03-03 22:29:44', '2023-03-03 22:29:44'),
(302, NULL, 'tort', 'yes', 'm_10', 'walid888', '2023-03-03 22:29:48', '2023-03-03 22:29:48'),
(303, NULL, 'tort', 'yes', 'm_11', 'walid888', '2023-03-03 22:29:54', '2023-03-03 22:29:54'),
(304, NULL, 'tort', 'yes', 'm_12', 'walid888', '2023-03-03 22:30:09', '2023-03-03 22:30:09'),
(305, NULL, 'tort', 'yes', 'm_13', 'walid888', '2023-03-03 22:30:16', '2023-03-03 22:30:16'),
(306, NULL, 'tort', 'yes', 'm_14', 'walid888', '2023-03-03 22:30:20', '2023-03-03 22:30:20'),
(307, NULL, 'tort', 'yes', 'm_15s', 'walid888', '2023-03-09 15:15:05', '2023-03-03 22:30:23'),
(310, 'markUS', NULL, 'no', 'hio', 'walid888', '2023-03-04 00:19:10', '2023-03-04 00:19:10'),
(311, 'testUSa', NULL, 'no', 'campaign update: your campaign is camp', 'AutoGenerated', '2023-03-04 00:19:29', '2023-03-04 00:19:29'),
(312, 'walidali', NULL, 'no', 'target update: your target is 0', 'AutoGenerated', '2023-03-04 00:46:23', '2023-03-04 00:46:23'),
(313, 'Yoshi', NULL, 'no', 'dedication update: you have 0 EPG dedication', 'AutoGenerated', '2023-03-04 00:50:52', '2023-03-04 00:50:52'),
(314, 'Shad', NULL, 'no', 'dedication update: you have 0 EPG dedication', 'AutoGenerated', '2023-03-04 00:50:52', '2023-03-04 00:50:52'),
(315, 'Clarke', NULL, 'no', 'dedication update: you have 0 EPG dedication', 'AutoGenerated', '2023-03-04 00:50:52', '2023-03-04 00:50:52'),
(316, 'Cassandra', NULL, 'no', 'dedication update: you have 0 EPG dedication', 'AutoGenerated', '2023-03-04 00:50:52', '2023-03-04 00:50:52'),
(317, 'Ignatius', NULL, 'no', 'dedication update: you have 0 EPG dedication', 'AutoGenerated', '2023-03-04 00:50:52', '2023-03-04 00:50:52'),
(318, 'Boris', NULL, 'no', 'dedication update: you have 0 EPG dedication', 'AutoGenerated', '2023-03-04 00:50:52', '2023-03-04 00:50:52'),
(319, 'Jonas', NULL, 'no', 'dedication update: you have 0 EPG dedication', 'AutoGenerated', '2023-03-04 00:50:52', '2023-03-04 00:50:52'),
(320, 'Fulton', NULL, 'no', 'dedication update: you have 0 EPG dedication', 'AutoGenerated', '2023-03-04 00:50:53', '2023-03-04 00:50:53'),
(321, 'Dustin', NULL, 'no', 'dedication update: you have 0 EPG dedication', 'AutoGenerated', '2023-03-04 00:50:53', '2023-03-04 00:50:53'),
(322, 'Montana', NULL, 'no', 'dedication update: you have 0 EPG dedication', 'AutoGenerated', '2023-03-04 00:50:53', '2023-03-04 00:50:53'),
(323, 'walidali', NULL, 'no', 'target update: your target is 3', 'AutoGenerated', '2023-03-04 00:51:27', '2023-03-04 00:51:27'),
(324, 'testUS', NULL, 'no', 'target update: your target is 5', 'AutoGenerated', '2023-03-04 00:51:27', '2023-03-04 00:51:27'),
(325, 'markUS', NULL, 'no', 'target update: your target is 565', 'AutoGenerated', '2023-03-04 00:51:27', '2023-03-04 00:51:27'),
(326, 'frank', NULL, 'no', 'target update: your target is 343', 'AutoGenerated', '2023-03-04 00:51:28', '2023-03-04 00:51:28'),
(327, 'testUSa', NULL, 'no', 'target update: your target is 34', 'AutoGenerated', '2023-03-04 00:51:28', '2023-03-04 00:51:28'),
(328, 'Yoshi', NULL, 'no', 'target update: your target is 56', 'AutoGenerated', '2023-03-04 00:51:28', '2023-03-04 00:51:28'),
(329, 'walidali', NULL, 'no', 'hi man', 'walid888', '2023-03-04 00:51:53', '2023-03-04 00:51:53'),
(331, 'walidali', NULL, 'no', 'target update: your target is 4', 'AutoGenerated', '2023-03-06 23:29:32', '2023-03-06 23:29:32'),
(332, 'walidali', NULL, 'no', 'target update: your target is 6', 'AutoGenerated', '2023-03-07 00:51:25', '2023-03-07 00:51:25'),
(333, 'testUS', NULL, 'no', 'hi tes', 'walid888', '2023-03-07 00:52:15', '2023-03-07 00:52:15'),
(334, 'testUS', NULL, 'no', 'what', 'walid888', '2023-03-07 00:52:24', '2023-03-07 00:52:24'),
(335, 'walidali', NULL, 'no', 'hiii', 'walid888', '2023-03-07 00:52:34', '2023-03-07 00:52:34'),
(336, 'walidali', NULL, 'no', 'target update: your target is 8', 'AutoGenerated', '2023-03-07 00:52:46', '2023-03-07 00:52:46'),
(337, 'broUS', NULL, 'yes', 'dedication update: you have 2 EPG dedication', 'AutoGenerated', '2023-03-07 00:53:19', '2023-03-07 00:53:19'),
(338, 'broUS', NULL, 'yes', 'hi man', 'walid888', '2023-03-07 00:54:16', '2023-03-07 00:54:16'),
(339, 'broUS', NULL, 'yes', 'lolo', 'walid888', '2023-03-07 01:16:06', '2023-03-07 01:16:06'),
(340, 'broUS', NULL, 'yes', 'target update: your target is 2', 'AutoGenerated', '2023-03-07 19:03:55', '2023-03-07 19:03:55'),
(341, 'broUS', NULL, 'yes', 'aola', 'walid888', '2023-03-07 19:29:40', '2023-03-07 19:29:40'),
(342, 'broUS', NULL, 'yes', 'joj', 'walid888', '2023-03-07 19:30:28', '2023-03-07 19:30:28'),
(343, 'broUS', NULL, 'yes', 'target update: your target is 0', 'AutoGenerated', '2023-03-07 19:30:41', '2023-03-07 19:30:41'),
(344, 'broUS', NULL, 'yes', 'karteh jamp', 'walid888', '2023-03-09 15:12:49', '2023-03-07 19:45:25'),
(345, 'broUS', NULL, 'yes', 'Entry time update:  your Entry time is  2023-01-01 20:00', 'AutoGenerated', '2023-03-07 20:28:39', '2023-03-07 20:28:39'),
(351, 'broUS', NULL, 'yes', 'leave time update:  your leave time is  2023-01-01 01:00', 'AutoGenerated', '2023-03-08 01:23:20', '2023-03-08 01:23:20'),
(352, 'walidali', NULL, 'no', 'target update: your target is 6', 'AutoGenerated', '2023-03-08 19:31:47', '2023-03-08 19:31:47'),
(353, 'broUS', NULL, 'yes', 'hi there see time', 'walid888', '2023-03-09 15:06:05', '2023-03-08 19:36:06'),
(355, 'testUS', NULL, 'no', 'jojojojoj', 'walid888', '2023-03-08 20:43:12', '2023-03-08 20:42:29'),
(356, 'Yoshi', NULL, 'no', 'campaign update: your campaign is new camp', 'AutoGenerated', '2023-03-08 21:18:42', '2023-03-08 21:18:42'),
(357, NULL, 'new camp', 'no', 'hi yalls', 'walid888', '2023-03-09 15:16:48', '2023-03-08 21:18:52'),
(358, NULL, 'tort', 'yes', 'Lorem ipsum dolor sit amet consectetur adipisicing elit.', 'walid888', '2023-03-08 21:27:20', '2023-03-08 21:26:58'),
(359, 'walidali', NULL, 'no', 'target update: your target is 4', 'AutoGenerated', '2023-03-08 21:43:47', '2023-03-08 21:43:47'),
(360, 'walidali', NULL, 'no', 'target update: your target is 6', 'AutoGenerated', '2023-03-08 21:44:13', '2023-03-08 21:44:13'),
(361, 'walidali', NULL, 'no', 'target update: your target is 8', 'AutoGenerated', '2023-03-08 21:46:18', '2023-03-08 21:46:18'),
(362, 'testUS', NULL, 'no', 'target update: your target is 3', 'AutoGenerated', '2023-03-08 21:46:18', '2023-03-08 21:46:18'),
(363, 'walidali', NULL, 'no', 'target update: your target is 10', 'AutoGenerated', '2023-03-08 22:01:06', '2023-03-08 22:01:06'),
(364, 'walidali', NULL, 'no', 'target update: your target is 12', 'AutoGenerated', '2023-03-08 22:01:12', '2023-03-08 22:01:12'),
(365, 'testUS', NULL, 'no', 'target update: your target is 1', 'AutoGenerated', '2023-03-08 22:01:12', '2023-03-08 22:01:12'),
(366, 'leoUS', NULL, 'yes', 'this is a test mesg for leoUS 12.23', 'broUS', '2023-03-09 15:35:36', '2023-03-09 15:35:36'),
(367, 'leoUS', NULL, 'yes', 'this is a test mesg for leoUS 12.23', 'broUS', '2023-03-09 15:35:49', '2023-03-09 15:35:49'),
(368, 'walidali', NULL, 'no', 'Entry time update:  your Entry time is  2023-01-01 19:00', 'AutoGenerated', '2023-03-09 17:35:09', '2023-03-09 17:35:09'),
(369, 'walidali', NULL, 'no', 'leave time update:  your leave time is  2023-01-01 02:00', 'AutoGenerated', '2023-03-09 17:35:09', '2023-03-09 17:35:09'),
(370, 'testUS', NULL, 'no', 'Entry time update:  your Entry time is  2023-01-01 20:00', 'AutoGenerated', '2023-03-09 17:35:09', '2023-03-09 17:35:09'),
(371, 'testUS', NULL, 'no', 'leave time update:  your leave time is  2023-01-01 02:00', 'AutoGenerated', '2023-03-09 17:35:09', '2023-03-09 17:35:09'),
(372, 'markUS', NULL, 'no', 'Entry time update:  your Entry time is  2023-01-01 07:00', 'AutoGenerated', '2023-03-09 17:35:09', '2023-03-09 17:35:09'),
(373, 'markUS', NULL, 'no', 'leave time update:  your leave time is  2023-01-01 00:00', 'AutoGenerated', '2023-03-09 17:35:09', '2023-03-09 17:35:09'),
(374, 'testUSa', NULL, 'no', 'Entry time update:  your Entry time is  2023-01-01 20:00', 'AutoGenerated', '2023-03-09 17:35:10', '2023-03-09 17:35:10'),
(375, 'testUSa', NULL, 'no', 'leave time update:  your leave time is  2023-01-01 02:00', 'AutoGenerated', '2023-03-09 17:35:10', '2023-03-09 17:35:10'),
(376, 'broUS', NULL, 'yes', 'Entry time update:  your Entry time is  2023-01-01 20:00', 'AutoGenerated', '2023-03-09 17:35:10', '2023-03-09 17:35:10'),
(377, 'broUS', NULL, 'yes', 'leave time update:  your leave time is  2023-01-01 01:00', 'AutoGenerated', '2023-03-09 17:35:10', '2023-03-09 17:35:10'),
(378, 'frank', NULL, 'no', 'Entry time update:  your Entry time is  2023-01-01 08:00', 'AutoGenerated', '2023-03-09 17:35:10', '2023-03-09 17:35:10'),
(379, 'frank', NULL, 'no', 'leave time update:  your leave time is  2023-01-01 02:00', 'AutoGenerated', '2023-03-09 17:35:10', '2023-03-09 17:35:10'),
(380, 'Yoshi', NULL, 'no', 'Entry time update:  your Entry time is  2023-01-01 00:00', 'AutoGenerated', '2023-03-09 17:35:10', '2023-03-09 17:35:10'),
(381, 'Yoshi', NULL, 'no', 'leave time update:  your leave time is  2023-01-01 00:00', 'AutoGenerated', '2023-03-09 17:35:10', '2023-03-09 17:35:10'),
(382, 'Shad', NULL, 'no', 'Entry time update:  your Entry time is  2023-01-01 00:00', 'AutoGenerated', '2023-03-09 17:35:10', '2023-03-09 17:35:10'),
(383, 'Shad', NULL, 'no', 'leave time update:  your leave time is  2023-01-01 00:00', 'AutoGenerated', '2023-03-09 17:35:10', '2023-03-09 17:35:10'),
(384, 'Clarke', NULL, 'no', 'Entry time update:  your Entry time is  2023-01-01 00:00', 'AutoGenerated', '2023-03-09 17:35:10', '2023-03-09 17:35:10'),
(385, 'Clarke', NULL, 'no', 'leave time update:  your leave time is  2023-01-01 00:00', 'AutoGenerated', '2023-03-09 17:35:10', '2023-03-09 17:35:10'),
(386, 'Cassandra', NULL, 'no', 'Entry time update:  your Entry time is  2023-01-01 00:00', 'AutoGenerated', '2023-03-09 17:35:10', '2023-03-09 17:35:10'),
(387, 'Cassandra', NULL, 'no', 'leave time update:  your leave time is  2023-01-01 00:00', 'AutoGenerated', '2023-03-09 17:35:10', '2023-03-09 17:35:10'),
(388, 'Ignatius', NULL, 'no', 'Entry time update:  your Entry time is  2023-01-01 00:00', 'AutoGenerated', '2023-03-09 17:35:10', '2023-03-09 17:35:10'),
(389, 'Ignatius', NULL, 'no', 'leave time update:  your leave time is  2023-01-01 00:00', 'AutoGenerated', '2023-03-09 17:35:11', '2023-03-09 17:35:11'),
(390, 'Boris', NULL, 'no', 'Entry time update:  your Entry time is  2023-01-01 00:00', 'AutoGenerated', '2023-03-09 17:35:11', '2023-03-09 17:35:11'),
(391, 'Boris', NULL, 'no', 'leave time update:  your leave time is  2023-01-01 00:00', 'AutoGenerated', '2023-03-09 17:35:11', '2023-03-09 17:35:11'),
(392, 'Jonas', NULL, 'no', 'Entry time update:  your Entry time is  2023-01-01 00:00', 'AutoGenerated', '2023-03-09 17:35:11', '2023-03-09 17:35:11'),
(393, 'Jonas', NULL, 'no', 'leave time update:  your leave time is  2023-01-01 00:00', 'AutoGenerated', '2023-03-09 17:35:11', '2023-03-09 17:35:11'),
(394, 'Fulton', NULL, 'no', 'Entry time update:  your Entry time is  2023-01-01 00:00', 'AutoGenerated', '2023-03-09 17:35:11', '2023-03-09 17:35:11'),
(395, 'Fulton', NULL, 'no', 'leave time update:  your leave time is  2023-01-01 00:00', 'AutoGenerated', '2023-03-09 17:35:11', '2023-03-09 17:35:11'),
(396, 'Dustin', NULL, 'no', 'Entry time update:  your Entry time is  2023-01-01 00:00', 'AutoGenerated', '2023-03-09 17:35:11', '2023-03-09 17:35:11'),
(397, 'Dustin', NULL, 'no', 'leave time update:  your leave time is  2023-01-01 00:00', 'AutoGenerated', '2023-03-09 17:35:11', '2023-03-09 17:35:11'),
(398, 'Montana', NULL, 'no', 'Entry time update:  your Entry time is  2023-01-01 00:00', 'AutoGenerated', '2023-03-09 17:35:11', '2023-03-09 17:35:11'),
(399, 'Montana', NULL, 'no', 'leave time update:  your leave time is  2023-01-01 00:00', 'AutoGenerated', '2023-03-09 17:35:11', '2023-03-09 17:35:11'),
(403, 'walidali', NULL, 'no', 'salary update: your salary is 3', 'AutoGenerated', '2023-03-11 20:39:57', '2023-03-11 20:39:57'),
(404, 'WalidAliAli', NULL, 'no', 'Entry time update:  your Entry time is  2023-01-01 00:00:00', 'AutoGenerated', '2023-03-13 11:58:47', '2023-03-13 11:58:47'),
(405, 'WalidAliAli', NULL, 'no', 'leave time update:  your leave time is  2023-01-01 00:00:00', 'AutoGenerated', '2023-03-13 11:58:48', '2023-03-13 11:58:48'),
(406, 'WalidAliAli', NULL, 'no', 'Entry time update:  your Entry time is  2023-01-01 00:00:00', 'AutoGenerated', '2023-03-13 11:59:12', '2023-03-13 11:59:12'),
(407, 'WalidAliAli', NULL, 'no', 'leave time update:  your leave time is  2023-01-01 00:00:00', 'AutoGenerated', '2023-03-13 11:59:12', '2023-03-13 11:59:12'),
(408, 'WalidAliAli', NULL, 'no', 'Entry time update:  your Entry time is  2023-01-01 00:00:00', 'AutoGenerated', '2023-03-13 11:59:54', '2023-03-13 11:59:54'),
(409, 'WalidAliAli', NULL, 'no', 'leave time update:  your leave time is  2023-01-01 00:00:00', 'AutoGenerated', '2023-03-13 11:59:54', '2023-03-13 11:59:54'),
(410, 'walidali', NULL, 'no', 'salary update: your salary is 5', 'AutoGenerated', '2023-03-13 12:00:16', '2023-03-13 12:00:16'),
(411, 'walidali', NULL, 'no', 'target update: your target is 10', 'AutoGenerated', '2023-03-13 12:00:19', '2023-03-13 12:00:19'),
(412, 'WalidAliAli', NULL, 'no', 'Entry time update:  your Entry time is  2023-01-01 00:00:00', 'AutoGenerated', '2023-03-13 12:00:20', '2023-03-13 12:00:20'),
(413, 'WalidAliAli', NULL, 'no', 'leave time update:  your leave time is  2023-01-01 00:00:00', 'AutoGenerated', '2023-03-13 12:00:20', '2023-03-13 12:00:20'),
(414, 'WalidAliAli', NULL, 'no', 'Entry time update:  your Entry time is  2023-01-01 00:00:00', 'AutoGenerated', '2023-03-13 12:01:28', '2023-03-13 12:01:28'),
(415, 'WalidAliAli', NULL, 'no', 'leave time update:  your leave time is  2023-01-01 00:00:00', 'AutoGenerated', '2023-03-13 12:01:28', '2023-03-13 12:01:28'),
(416, 'WalidAliAli', NULL, 'no', 'target update: your target is 0', 'AutoGenerated', '2023-03-13 12:05:06', '2023-03-13 12:05:06'),
(417, 'WalidAliAli', NULL, 'no', 'dedication update: you have 0 EPG dedication', 'AutoGenerated', '2023-03-13 12:05:06', '2023-03-13 12:05:06'),
(418, 'WalidAliAli', NULL, 'no', 'Entry time update:  your Entry time is  2023-01-01 00:00:00', 'AutoGenerated', '2023-03-13 12:05:06', '2023-03-13 12:05:06'),
(419, 'WalidAliAli', NULL, 'no', 'leave time update:  your leave time is  2023-01-01 00:00:00', 'AutoGenerated', '2023-03-13 12:05:06', '2023-03-13 12:05:06'),
(420, 'wellyUS123', NULL, 'no', 'target update: your target is 0', 'AutoGenerated', '2023-03-13 12:05:06', '2023-03-13 12:05:06'),
(421, 'wellyUS123', NULL, 'no', 'dedication update: you have 0 EPG dedication', 'AutoGenerated', '2023-03-13 12:05:06', '2023-03-13 12:05:06'),
(422, 'wellyUS123', NULL, 'no', 'Entry time update:  your Entry time is  2023-01-01 ', 'AutoGenerated', '2023-03-13 12:14:13', '2023-03-13 12:14:13'),
(423, 'wellyUS123', NULL, 'no', 'leave time update:  your leave time is  2023-01-01 ', 'AutoGenerated', '2023-03-13 12:14:13', '2023-03-13 12:14:13'),
(424, 'markUS', NULL, 'no', 'hi marl', 'walid888', '2023-03-13 16:47:08', '2023-03-13 16:47:08'),
(425, 'walidali', NULL, 'no', 'salary update: your salary is 3', 'AutoGenerated', '2023-03-14 10:40:55', '2023-03-14 10:40:55'),
(426, 'loloLOLO', NULL, 'no', 'target update: your target is 0', 'AutoGenerated', '2023-03-14 10:40:55', '2023-03-14 10:40:55'),
(427, 'loloLOLO', NULL, 'no', 'dedication update: you have 0 EPG dedication', 'AutoGenerated', '2023-03-14 10:40:56', '2023-03-14 10:40:56'),
(428, 'loloLOLO', NULL, 'no', 'Entry time update:  your Entry time is  2023-01-01 00:00:00', 'AutoGenerated', '2023-03-14 10:40:56', '2023-03-14 10:40:56'),
(429, 'loloLOLO', NULL, 'no', 'leave time update:  your leave time is  2023-01-01 00:00:00', 'AutoGenerated', '2023-03-14 10:40:56', '2023-03-14 10:40:56'),
(430, 'ssosossosos', NULL, 'no', 'target update: your target is 0', 'AutoGenerated', '2023-03-14 10:40:56', '2023-03-14 10:40:56'),
(431, 'ssosossosos', NULL, 'no', 'dedication update: you have 0 EPG dedication', 'AutoGenerated', '2023-03-14 10:40:56', '2023-03-14 10:40:56'),
(432, 'ssosossosos', NULL, 'no', 'Entry time update:  your Entry time is  2023-01-01 00:00:00', 'AutoGenerated', '2023-03-14 10:40:56', '2023-03-14 10:40:56'),
(433, 'ssosossosos', NULL, 'no', 'leave time update:  your leave time is  2023-01-01 00:00:00', 'AutoGenerated', '2023-03-14 10:40:56', '2023-03-14 10:40:56'),
(434, 'kokoKOKO', NULL, 'no', 'target update: your target is 0', 'AutoGenerated', '2023-03-14 10:40:56', '2023-03-14 10:40:56'),
(435, 'kokoKOKO', NULL, 'no', 'dedication update: you have 0 EPG dedication', 'AutoGenerated', '2023-03-14 10:40:56', '2023-03-14 10:40:56'),
(436, 'kokoKOKO', NULL, 'no', 'Entry time update:  your Entry time is  2023-01-01 00:00:00', 'AutoGenerated', '2023-03-14 10:40:56', '2023-03-14 10:40:56'),
(437, 'kokoKOKO', NULL, 'no', 'leave time update:  your leave time is  2023-01-01 00:00:00', 'AutoGenerated', '2023-03-14 10:40:56', '2023-03-14 10:40:56'),
(438, 'walidali', NULL, 'no', 'salary update: your salary is 0', 'AutoGenerated', '2023-03-14 12:19:52', '2023-03-14 12:19:52'),
(439, 'Yoshi', NULL, 'no', 'salary update: your salary is 0', 'AutoGenerated', '2023-03-14 12:19:53', '2023-03-14 12:19:53'),
(440, 'Shad', NULL, 'no', 'salary update: your salary is 0', 'AutoGenerated', '2023-03-14 12:19:53', '2023-03-14 12:19:53'),
(441, 'Clarke', NULL, 'no', 'salary update: your salary is 0', 'AutoGenerated', '2023-03-14 12:19:53', '2023-03-14 12:19:53'),
(442, 'Cassandra', NULL, 'no', 'salary update: your salary is 0', 'AutoGenerated', '2023-03-14 12:19:53', '2023-03-14 12:19:53'),
(443, 'Ignatius', NULL, 'no', 'salary update: your salary is 0', 'AutoGenerated', '2023-03-14 12:19:53', '2023-03-14 12:19:53'),
(444, 'Boris', NULL, 'no', 'salary update: your salary is 0', 'AutoGenerated', '2023-03-14 12:19:53', '2023-03-14 12:19:53'),
(445, 'Jonas', NULL, 'no', 'salary update: your salary is 0', 'AutoGenerated', '2023-03-14 12:19:54', '2023-03-14 12:19:54'),
(446, 'Fulton', NULL, 'no', 'salary update: your salary is 0', 'AutoGenerated', '2023-03-14 12:19:54', '2023-03-14 12:19:54'),
(447, 'Dustin', NULL, 'no', 'salary update: your salary is 0', 'AutoGenerated', '2023-03-14 12:19:54', '2023-03-14 12:19:54'),
(448, 'Montana', NULL, 'no', 'salary update: your salary is 0', 'AutoGenerated', '2023-03-14 12:19:54', '2023-03-14 12:19:54'),
(449, 'wellyUS123', NULL, 'no', 'salary update: your salary is 0', 'AutoGenerated', '2023-03-14 12:19:54', '2023-03-14 12:19:54'),
(450, 'walidali', NULL, 'no', 'dedication update: you have 5 EPG dedication', 'AutoGenerated', '2023-03-14 12:22:16', '2023-03-14 12:22:16'),
(451, 'walidali', NULL, 'no', 'dedication update: you have 0 EPG dedication', 'AutoGenerated', '2023-03-14 12:22:19', '2023-03-14 12:22:19'),
(452, 'broUS', NULL, 'yes', 'dedication update: you have 0 EPG dedication', 'AutoGenerated', '2023-03-14 12:22:20', '2023-03-14 12:22:20'),
(453, 'walidali', NULL, 'no', 'hi man how are u', 'walid888', '2023-03-14 12:25:03', '2023-03-14 12:24:52'),
(454, 'broUS', NULL, 'yes', 'Entry time update:  your Entry time is  2023-01-01 08:00', 'AutoGenerated', '2023-03-14 12:27:04', '2023-03-14 12:27:04'),
(463, 'broUS', NULL, 'yes', 'leave time update:  your leave time is  2023-01-01 17:00', 'AutoGenerated', '2023-03-14 14:24:15', '2023-03-14 14:24:15'),
(466, 'broUS', NULL, 'yes', 'leave time update:  your leave time is  2023-01-01 07:00', 'AutoGenerated', '2023-03-14 14:24:56', '2023-03-14 14:24:56'),
(467, 'broUS', NULL, 'yes', 'leave time update:  your leave time is  2023-01-01 09:00', 'AutoGenerated', '2023-03-14 14:28:52', '2023-03-14 14:28:52'),
(468, 'leoUS', NULL, 'yes', 'broUS got in late', 'admin_alert', '2023-03-14 14:32:13', '2023-03-14 14:32:13'),
(469, 'walid888', NULL, 'yes', 'broUS got in late', 'admin_alert', '2023-03-14 14:32:13', '2023-03-14 14:32:13'),
(470, 'broUS', NULL, 'yes', 'leave time update:  your leave time is  2023-01-01 21:00', 'AutoGenerated', '2023-03-14 14:33:12', '2023-03-14 14:33:12'),
(471, 'leoUS', NULL, 'yes', 'broUS got in late', 'admin_alert', '2023-03-14 14:33:38', '2023-03-14 14:33:38'),
(472, 'walid888', NULL, 'yes', 'broUS got in late', 'admin_alert', '2023-03-14 14:33:38', '2023-03-14 14:33:38'),
(473, 'leoUS', NULL, 'yes', 'broUS left erlay', 'admin_alert', '2023-03-14 14:33:51', '2023-03-14 14:33:51'),
(474, 'walid888', NULL, 'yes', 'broUS left erlay', 'admin_alert', '2023-03-14 14:33:51', '2023-03-14 14:33:51'),
(475, 'broUS', NULL, 'yes', 'waht is up bro', 'walid888', '2023-03-14 15:05:31', '2023-03-14 15:05:31'),
(476, 'broUS', NULL, 'yes', 'a', 'walid888', '2023-03-14 15:05:39', '2023-03-14 15:05:39'),
(477, 'broUS', NULL, 'yes', 'b', 'walid888', '2023-03-14 15:05:42', '2023-03-14 15:05:42'),
(478, 'broUS', NULL, 'yes', 'c', 'walid888', '2023-03-14 15:05:43', '2023-03-14 15:05:43'),
(479, 'broUS', NULL, 'yes', 'd', 'walid888', '2023-03-14 15:05:44', '2023-03-14 15:05:44'),
(480, 'broUS', NULL, 'yes', 'e', 'walid888', '2023-03-14 15:05:45', '2023-03-14 15:05:45'),
(481, 'broUS', NULL, 'yes', 'f', 'walid888', '2023-03-14 15:05:46', '2023-03-14 15:05:46'),
(482, 'broUS', NULL, 'yes', 'g', 'walid888', '2023-03-14 15:05:48', '2023-03-14 15:05:48'),
(483, 'broUS', NULL, 'yes', 'h', 'walid888', '2023-03-14 15:05:50', '2023-03-14 15:05:50'),
(484, 'broUS', NULL, 'yes', 'i', 'walid888', '2023-03-14 15:05:52', '2023-03-14 15:05:52'),
(485, 'broUS', NULL, 'yes', 'g', 'walid888', '2023-03-14 15:05:53', '2023-03-14 15:05:53'),
(486, 'broUS', NULL, 'yes', 'k', 'walid888', '2023-03-14 15:05:55', '2023-03-14 15:05:55'),
(487, 'broUS', NULL, 'yes', 'k', 'walid888', '2023-03-14 15:05:59', '2023-03-14 15:05:59'),
(488, 'leoUS', NULL, 'yes', 'broUS got in late', 'admin_alert', '2023-03-14 17:06:01', '2023-03-14 17:06:01'),
(489, 'walid888', NULL, 'yes', 'broUS got in late', 'admin_alert', '2023-03-14 17:06:01', '2023-03-14 17:06:01'),
(490, 'testUSa', NULL, 'no', 'dedication update: you have 2 EPG dedication', 'AutoGenerated', '2023-03-14 17:18:55', '2023-03-14 17:18:55'),
(491, 'walidali', NULL, 'no', 'campaign update: your campaign is hhh', 'AutoGenerated', '2023-03-15 15:07:17', '2023-03-15 15:07:17'),
(492, 'walidali', NULL, 'no', 'target update: your target is 13', 'AutoGenerated', '2023-03-15 15:07:22', '2023-03-15 15:07:22'),
(493, 'walidali', NULL, 'no', 'salary update: your salary is 2', 'AutoGenerated', '2023-03-15 15:07:25', '2023-03-15 15:07:25'),
(494, 'walidali', NULL, 'no', 'dedication update: you have 3 EPG dedication', 'AutoGenerated', '2023-03-15 15:07:28', '2023-03-15 15:07:28'),
(495, 'walidali', NULL, 'no', 'target update: your target is 0', 'AutoGenerated', '2023-03-15 15:07:32', '2023-03-15 15:07:32'),
(496, 'testUS', NULL, 'no', 'target update: your target is 0', 'AutoGenerated', '2023-03-15 15:07:32', '2023-03-15 15:07:32'),
(497, 'markUS', NULL, 'no', 'target update: your target is 0', 'AutoGenerated', '2023-03-15 15:07:32', '2023-03-15 15:07:32'),
(498, 'frank', NULL, 'no', 'target update: your target is 0', 'AutoGenerated', '2023-03-15 15:07:32', '2023-03-15 15:07:32'),
(499, 'testUSa', NULL, 'no', 'target update: your target is 0', 'AutoGenerated', '2023-03-15 15:07:32', '2023-03-15 15:07:32'),
(500, 'Yoshi', NULL, 'no', 'target update: your target is 0', 'AutoGenerated', '2023-03-15 15:07:32', '2023-03-15 15:07:32'),
(501, 'walidali', NULL, 'no', 'campaign update: your campaign is ', 'AutoGenerated', '2023-03-15 15:07:38', '2023-03-15 15:07:38'),
(502, 'walidali', NULL, 'no', 'campaign update: your campaign is  ', 'AutoGenerated', '2023-03-15 15:07:44', '2023-03-15 15:07:44'),
(503, 'walidali', NULL, 'no', 'campaign update: your campaign is NOT_SET', 'AutoGenerated', '2023-03-15 15:08:26', '2023-03-15 15:08:26'),
(504, 'broUS', NULL, 'no', 'hi bro 03/17/2023', 'walid888', '2023-03-17 11:22:34', '2023-03-17 11:22:34'),
(505, 'broUS', NULL, 'no', 'hi', 'leoUS', '2023-03-17 11:32:07', '2023-03-17 11:32:07'),
(506, NULL, 'tort', 'no', 'hi', 'leoUS', '2023-03-17 11:33:11', '2023-03-17 11:33:11');

-- --------------------------------------------------------

--
-- Table structure for table `ar_test`
--

CREATE TABLE `ar_test` (
  `id` int(11) NOT NULL,
  `text` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `ar_test`
--

INSERT INTO `ar_test` (`id`, `text`) VALUES
(1, 'وليد');

-- --------------------------------------------------------

--
-- Table structure for table `attendance`
--

CREATE TABLE `attendance` (
  `id` int(11) NOT NULL,
  `user_name` varchar(100) NOT NULL,
  `user_id` int(11) NOT NULL,
  `day_date` date NOT NULL,
  `is_it_over` varchar(100) NOT NULL,
  `time_in` datetime DEFAULT NULL,
  `time_out` datetime DEFAULT NULL,
  `excuse` varchar(255) DEFAULT NULL,
  `created_at` datetime DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;

--
-- Dumping data for table `attendance`
--

INSERT INTO `attendance` (`id`, `user_name`, `user_id`, `day_date`, `is_it_over`, `time_in`, `time_out`, `excuse`, `created_at`) VALUES
(75, 'testUS', 13, '2023-02-23', 'yes', '2023-02-23 20:00:00', '2023-02-23 02:00:00', NULL, '2023-02-23 00:53:30'),
(76, 'testUS', 13, '2023-02-22', 'yes', '2023-02-22 00:53:30', '2023-02-22 02:00:00', NULL, '2023-02-22 00:53:30'),
(77, 'testUS', 13, '2023-02-21', 'yes', '2023-02-21 00:53:30', '2023-02-21 07:53:30', NULL, '2023-02-21 00:53:30'),
(78, 'testUS', 13, '2023-02-20', 'yes', '2023-02-20 00:53:30', '2023-02-20 05:00:00', NULL, '2023-02-20 00:53:30'),
(79, 'testUS', 13, '2023-02-19', 'yes', '2023-02-19 00:53:30', '2023-02-19 05:53:30', NULL, '2023-02-19 00:53:30'),
(80, 'testUS', 13, '2023-02-18', 'yes', '2023-02-18 19:00:00', '2023-02-18 05:00:00', NULL, '2023-02-18 00:53:30'),
(81, 'testUS', 13, '2023-02-26', 'yes', '2023-02-25 01:20:53', '2023-02-25 01:20:56', NULL, '2023-02-25 01:20:53'),
(84, 'testUS', 13, '2023-02-25', 'yes', '2023-02-25 20:00:00', '2023-02-25 02:00:00', NULL, '2023-02-25 23:25:12'),
(85, 'walidali', 12, '2023-03-01', 'yes', '2023-03-01 00:34:08', '2023-03-01 00:34:09', NULL, '2023-03-01 00:34:08'),
(86, 'walid888', 11, '2023-03-04', 'yes', '2023-03-04 00:17:44', '2023-03-04 00:17:46', NULL, '2023-03-04 00:17:44'),
(106, 'testUS', 13, '2023-03-11', 'yes', '2023-03-11 13:26:09', '2023-03-11 13:26:11', NULL, '2023-03-11 13:26:09'),
(117, 'broUS', 17, '2023-03-14', 'yes', '2023-03-14 14:33:38', '2023-03-14 14:33:51', NULL, '2023-03-14 14:33:38');

-- --------------------------------------------------------

--
-- Table structure for table `tokens`
--

CREATE TABLE `tokens` (
  `id` int(255) NOT NULL,
  `name` varchar(255) NOT NULL,
  `token` varchar(255) NOT NULL,
  `purpose` varchar(255) DEFAULT 'NOT_SET',
  `exp` date NOT NULL,
  `created_at` date NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `tokens`
--

INSERT INTO `tokens` (`id`, `name`, `token`, `purpose`, `exp`, `created_at`) VALUES
(107, 'walid888', '$2y$10$aboeX0azAvOKV8jMaaAv0.vm.QXzduamq03HvQLfE5juL3i.K7FjS', 'remember_me', '2023-04-05', '2023-03-21');

-- --------------------------------------------------------

--
-- Table structure for table `users`
--

CREATE TABLE `users` (
  `id` int(11) NOT NULL,
  `first_name` varchar(100) NOT NULL,
  `last_name` varchar(100) NOT NULL,
  `email` varchar(100) NOT NULL,
  `user_name` varchar(100) NOT NULL,
  `gender` varchar(50) NOT NULL,
  `phone` varchar(15) NOT NULL,
  `address` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL,
  `campaign` varchar(255) DEFAULT 'NOT_SET',
  `rank` varchar(100) NOT NULL DEFAULT 'agint',
  `education` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `experience` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `target` int(255) DEFAULT NULL,
  `salary` int(255) DEFAULT NULL,
  `dedication` int(255) DEFAULT NULL,
  `enter_time` datetime DEFAULT NULL,
  `leave_time` datetime DEFAULT NULL,
  `created_at` datetime DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;

--
-- Dumping data for table `users`
--

INSERT INTO `users` (`id`, `first_name`, `last_name`, `email`, `user_name`, `gender`, `phone`, `address`, `password`, `campaign`, `rank`, `education`, `experience`, `target`, `salary`, `dedication`, `enter_time`, `leave_time`, `created_at`) VALUES
(9, 'leo', 'adams', 'leo@leo.leo', 'leoUS', 'male', '0941535901', 'shams', '$2y$10$Aq7MH71DAYxLFuDDT0GtmellgeTVp2xpon8wYrHi7L/vLiqd3Ff86', 'ngs', 'admin', 'my eduee', 'my exp', 12, 2000, 500, NULL, NULL, '2023-02-07 20:00:01'),
(11, 'walid', 'ali', 'walid@g.com', 'walid888', 'male', '0941535901', 'damscusssddd', '$2y$10$XQhPxro4Dw9fapMSapGq5.evUbxzO5dwK6Sj2zwDq4y12zExUYO/e', 'NOT_SET', 'admin', '???', 'wddqq', 11, 11, 500, NULL, NULL, '2023-02-07 22:51:11'),
(12, 'walid', 'ali', 'w@w.w', 'walidali', 'male', '1234567890', 'kkk', '$2y$10$9UuYeXGkjWbMUZjhPQsaXOQtoMgE4.otHdUbUbq0IbdziJlToP872', 'NOT_SET', 'agint', 'jj', 'jj', 0, 2, 3, '2023-01-01 19:00:00', '2023-01-01 02:00:00', '2023-02-13 19:19:13'),
(13, 'test', 'test', 'test@t.c', 'testUS', 'male', '123467890', 'damscus', '$2y$10$UudDlOBBk.Ik.enDLCSEqePE9gDp13pG485An7xblMQvhFlQAGN9S', 'tort', 'agint', 'koko', 'Write a summary of your experience:', 0, 0, 0, '2023-01-01 20:00:00', '2023-01-01 02:00:00', '2023-02-15 01:18:19'),
(14, 'mark', 'adams', 'm@m.m', 'markUS', 'female', '1234678', 'ddd', '$2y$10$vtgWKs02aLSHf3HsxKpHguWYB6KX7CP6TrNT5orzZuhsP2mYw5uXW', 'tort', 'agint', 'ssdd', 's', 0, 0, 0, '2023-01-01 07:00:00', '2023-01-01 00:00:00', '2023-02-15 22:48:17'),
(15, 'frank', 'f', 'f@f.f', 'frank', 'female', '123456', 'ssss', '$2y$10$pOiYrAitMu0g1f6.S.seFeaPUuI5fkRsxJ5PX/t2XNIpqQ1fjUn82', 'tort', 'agint', 'dddd', 'ffffff', 0, 0, 0, '2023-01-01 08:00:00', '2023-01-01 02:00:00', '2023-02-17 22:03:45'),
(17, 'bro', 'bro', 'b@b.b', 'broUS', 'male', '123456', '1xxx', '$2y$10$1nScZmLODg7/JZR58lyovuJGGRFhi3TzWcDN7mklYiBM9OWKqkJjy', 'tort', 'agint', 'asdas ????', 'test', 0, 0, 0, '2023-01-01 08:00:00', '2023-01-01 21:00:00', '2023-02-17 22:14:10'),
(18, 'test1', 'test1', 'test@t.c', 'testUSa', 'male', '123467890', 'damscus', '$2y$10$UudDlOBBk.Ik.enDLCSEqePE9gDp13pG485An7xblMQvhFlQAGN9S', 'camp', 'agint', 'Write a summary of your education', 'Write a summary of your experience:', 0, 0, 2, '2023-01-01 20:00:00', '2023-01-01 02:00:00', '2023-02-15 01:18:19'),
(24, 'Zahir Orr', 'Illiana Collier', 'dui.quis.accumsan@yahoo.couk', 'Yoshi', '', '6666666666', 'Göksun', '$2y$10$9UuYeXGkjWbMUZjhPQsaXOQtoMgE4.otHdUbUbq0IbdziJlToP872', 'new camp', 'agint', 'purus, accumsan interdum libero dui', 'egestas a, scelerisque sed, sapien.', 0, 0, 0, '2023-01-01 00:00:00', '2023-01-01 00:00:00', '2023-02-28 21:44:47'),
(25, 'Xander Juarez', 'Nelle Horne', 'fringilla.euismod@protonmail.org', 'Shad', '', '6666666666', 'Trento', '$2y$10$9UuYeXGkjWbMUZjhPQsaXOQtoMgE4.otHdUbUbq0IbdziJlToP872', 'NOT_SET', 'agint', 'felis ullamcorper viverra. Maecenas iaculis', 'risus, at fringilla purus mauris', 0, 0, 0, '2023-01-01 00:00:00', '2023-01-01 00:00:00', '2023-02-28 21:44:47'),
(26, 'Alisa Bernard', 'Jelani Maxwell', 'integer.eu.lacus@protonmail.couk', 'Clarke', '', '6666666666', 'River Valley', '$2y$10$9UuYeXGkjWbMUZjhPQsaXOQtoMgE4.otHdUbUbq0IbdziJlToP872', 'NOT_SET', 'agint', 'tellus lorem eu metus. In', 'accumsan laoreet ipsum. Curabitur consequat,', 0, 0, 0, '2023-01-01 00:00:00', '2023-01-01 00:00:00', '2023-02-28 21:44:47'),
(27, 'Rinah Witt', 'Chastity Cortez', 'odio.aliquam.vulputate@hotmail.net', 'Cassandra', '', '6666666666', 'Stratford', '$2y$10$9UuYeXGkjWbMUZjhPQsaXOQtoMgE4.otHdUbUbq0IbdziJlToP872', 'NOT_SET', 'agint', 'Mauris nulla. Integer urna. Vivamus', 'nec orci. Donec nibh. Quisque', 0, 0, 0, '2023-01-01 00:00:00', '2023-01-01 00:00:00', '2023-02-28 21:44:47'),
(28, 'Maggie Buckley', 'Yoko Kelly', 'sed.consequat@hotmail.net', 'Ignatius', '', '6666666666', 'Cork', '$2y$10$9UuYeXGkjWbMUZjhPQsaXOQtoMgE4.otHdUbUbq0IbdziJlToP872', 'NOT_SET', 'agint', 'eu dolor egestas rhoncus. Proin', 'ultrices a, auctor non, feugiat', 0, 0, 0, '2023-01-01 00:00:00', '2023-01-01 00:00:00', '2023-02-28 21:44:47'),
(29, 'Zeph Hinton', 'Hermione Ferrell', 'sed.hendrerit@google.org', 'Boris', '', '6666666666', 'Lowestoft', '$2y$10$9UuYeXGkjWbMUZjhPQsaXOQtoMgE4.otHdUbUbq0IbdziJlToP872', 'NOT_SET', 'agint', 'Phasellus nulla. Integer vulputate, risus', 'congue turpis. In condimentum. Donec', 0, 0, 0, '2023-01-01 00:00:00', '2023-01-01 00:00:00', '2023-02-28 21:44:47'),
(30, 'Hope Mays', 'Fritz Hawkins', 'rutrum.non@aol.com', 'Jonas', '', '6666666666', 'Clermont-Ferrand', '$2y$10$9UuYeXGkjWbMUZjhPQsaXOQtoMgE4.otHdUbUbq0IbdziJlToP872', 'NOT_SET', 'agint', 'Nunc lectus pede, ultrices a,', 'ut quam vel sapien imperdiet', 0, 0, 0, '2023-01-01 00:00:00', '2023-01-01 00:00:00', '2023-02-28 21:44:47'),
(31, 'Nomlanga Barber', 'Wesley Hayden', 'nunc.ac@aol.edu', 'Fulton', '', '6666666666', 'Bhimber', '$2y$10$9UuYeXGkjWbMUZjhPQsaXOQtoMgE4.otHdUbUbq0IbdziJlToP872', 'NOT_SET', 'agint', 'gravida sagittis. Duis gravida. Praesent', 'Cum sociis natoque penatibus et', 0, 0, 0, '2023-01-01 00:00:00', '2023-01-01 00:00:00', '2023-02-28 21:44:47'),
(32, 'Nero Carney', 'Britanney Anderson', 'lobortis.mauris@icloud.com', 'Dustin', '', '6666666666', 'Pinetown', '$2y$10$9UuYeXGkjWbMUZjhPQsaXOQtoMgE4.otHdUbUbq0IbdziJlToP872', 'NOT_SET', 'agint', 'Suspendisse sagittis. Nullam vitae diam.', 'posuere cubilia Curae Phasellus ornare.', 0, 0, 0, '2023-01-01 00:00:00', '2023-01-01 00:00:00', '2023-02-28 21:44:47'),
(33, 'Lesley Johnson', 'Kieran Morse', 'gravida@icloud.net', 'Montana', '', '6666666666', 'Gunsan', '$2y$10$9UuYeXGkjWbMUZjhPQsaXOQtoMgE4.otHdUbUbq0IbdziJlToP872', 'NOT_SET', 'agint', 'auctor ullamcorper, nisl arcu iaculis', 'elit. Etiam laoreet, libero et', 0, 0, 0, '2023-01-01 00:00:00', '2023-01-01 00:00:00', '2023-02-28 21:44:47'),
(39, 'walid', 'aali', 'w@w.ww', 'WalidAliAli', 'male', '0941535900', 'dam sy', '$2y$10$4I/3FTOJa2nDCQgKwDcFFebPH.xXM20c3FRjnQf44.KyQ9pT4S0mS', 'NOT_SET', 'agint', '', '', 0, 0, 0, '2023-01-01 00:00:00', '2023-01-01 00:00:00', '2023-03-11 20:53:45'),
(41, 'welly', 'welly', 'welly@U.S123', 'wellyUS123', 'male', '09415415934', 'sham', '$2y$10$Nf2uyL2rk1MLkRt9MFkg1.KIXu1pesvn27GpwdqS.wHYqjXpFbnpG', 'tort', 'agint', 'salary ', 'salary salary salary ', 0, 0, 0, '2023-01-01 00:00:00', '2023-01-01 00:00:00', '2023-03-13 09:16:44'),
(45, 'loloLOLO', 'loloLOLO', 'loloLO@L.O', 'loloLOLO', 'female', '0941535901', 'loloLOLO', '$2y$10$WmvgISQj.LY3ssvA0sCkUutHahvKf5Er1vZckA48pufAUrnQyi/4C', 'NOT_SET', 'agint', 'loloLOLO', 'loloLOLO', 0, 0, 0, '2023-01-01 00:00:00', '2023-01-01 00:00:00', '2023-03-13 14:10:38'),
(46, 'sos', 'sso', 's@s.s', 'ssosossosos', 'female', '1324567890', 'ssosos sosos', '$2y$10$QXli1qGJ6adrhS.Vf/iLA.SNHsI5slTEGpdNBWlP8x3iBJ62/xGXy', 'NOT_SET', 'agint', '', '', 0, 0, 0, '2023-01-01 00:00:00', '2023-01-01 00:00:00', '2023-03-13 15:31:05'),
(47, 'koko', 'koko', 'kokoKO@K.O', 'kokoKOKO', 'female', '0945678913', 'kokoKOKO kokoKOKO', '$2y$10$RBsxKLyVlnoaZ.XjixUQMeVHADXZdXzlKufYShnx7OziaXvReYOc6', 'NOT_SET', 'agint', 'kokoKOKO', 'kokoKOKO', 0, 0, 0, '2023-01-01 00:00:00', '2023-01-01 00:00:00', '2023-03-13 15:41:05');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `announcements`
--
ALTER TABLE `announcements`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `ar_test`
--
ALTER TABLE `ar_test`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `attendance`
--
ALTER TABLE `attendance`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `tokens`
--
ALTER TABLE `tokens`
  ADD UNIQUE KEY `id` (`id`);

--
-- Indexes for table `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `announcements`
--
ALTER TABLE `announcements`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=507;

--
-- AUTO_INCREMENT for table `ar_test`
--
ALTER TABLE `ar_test`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;

--
-- AUTO_INCREMENT for table `attendance`
--
ALTER TABLE `attendance`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=118;

--
-- AUTO_INCREMENT for table `tokens`
--
ALTER TABLE `tokens`
  MODIFY `id` int(255) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=108;

--
-- AUTO_INCREMENT for table `users`
--
ALTER TABLE `users`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=48;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
